# Stage 1: Build the React app
FROM node:16 as build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json from the main directory to the build context
COPY ../package.json ../package-lock.json ./

# Install dependencies
RUN npm install

# Copy the frontend code from the main directory
COPY . ./

# Build the React app for production
RUN npm run build

# Stage 2: Serve the React app using Nginx
FROM nginx:alpine

# Copy the production build from the build stage
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Run Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
